### ISSUE TITLE
插件bug及功能建议

### ISSUE THREAD

**Issue by AjianNie** [xjbeta/iina-plugin-danmaku#2]
macOS 11.6，弹幕插件版本0.1.0，iina版本1.3.1--plugin(8)
bug：加载弹幕后，插件菜单的修改无法实时响应，必须退出播放再重新加载弹幕文件
功能建议：选项栏里只看到了字体样式设置，是否可以修改大小和颜色吗？

**Comment by AjianYo** [comment]
macOS 11.6

**Comment by xjbeta** [comment]
插件系统功能有限  只能重现加载弹幕文件
大小可能可以 
颜色可能只能做到对直播弹幕有效  颜色取决于弹幕文件里的每条弹幕颜色

**Comment by AjianYo** [comment]
最后，调整弹幕时间的功能是否可以考虑一下

**Comment by AjianNie** [comment]
> 插件系统功能有限 只能重现加载弹幕文件
> 大小可能可以
> 颜色可能只能做到对直播弹幕有效 颜色取决于弹幕文件里的每条弹幕颜色

好的，明白。另外调整弹幕时间的功能是否可以考虑一下
